### ISSUE TITLE
OpenRouter incompatible with new openai API

### ISSUE THREAD

**Issue by jmizgajski** [OpenRouterTeam/openrouter-examples#3]
following code yields a `404` on `openai==1.3.5` which destroys compatibility with `langchain` and `llama_index`

```
client = OpenAI(
    default_headers={
        "HTTP-Referer": referer,
    },
    base_url="https://openrouter.ai/api/v1",
    api_key=open_router_key,
    max_retries = max_retries,
)
response = client.completions.create(
    prompt=prompt,
    model=self.model_name,
    max_tokens=self.max_tokens,
    temperature=self.temperature,
    n=self.n,
)
reply = response.choices[0].text
```
the request made looks like this in debugger - seems open-ai changed their endpoints

![image](https://github.com/OpenRouterTeam/openrouter-examples/assets/3886340/60889de8-eba8-4704-a254-ddb69ae8629f)

**Comment by louisgv** [comment]
Re:discord conversation, the python example is at: https://github.com/OpenRouterTeam/openrouter-examples-python/tree/main
